In [20]:
# coding: utf-8

import torch
import torchvision
import torch.nn as nn
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt    #グラフ出力用module
from PIL import Image
from sklearn.model_selection import train_test_split
import glob
import os
import csv
import torchvision

PATH = os.getcwd()
image_size=48
CONF = False

#seanセットフォルダ一覧取得
traindir = PATH + "\\dataset_seq2fix\\train"
testdir = PATH + "\\dataset_seq2fix\\test"

test_seans = glob.glob(testdir+"\\*")
train_seans = glob.glob(traindir+"\\*")
def resize(seans):
    for s in seans:
        img = glob.glob(s+"\\objectd*.png")[0]
        print(img)
        image = Image.open(img)
        image = image.resize((image_size, image_size))
        img_array = np.asarray(image)

        img = img.split("seq2fix\\")[1]
        img = img.split(".png")[0]
        print(img)
        image.save(PATH+"\\dataset_seq2fix\\"+img+"_resize48.png")

resize(test_seans)
resize(train_seans)

C:\Users\administrator\ObjectOperate\dataset_seq2fix\test\sean0012\objectd0008.png
test\sean0012\objectd0008
C:\Users\administrator\ObjectOperate\dataset_seq2fix\test\sean0022\objectd0012.png
test\sean0022\objectd0012
C:\Users\administrator\ObjectOperate\dataset_seq2fix\test\sean0024\objectd0014.png
test\sean0024\objectd0014
C:\Users\administrator\ObjectOperate\dataset_seq2fix\test\sean0026\objectd0014.png
test\sean0026\objectd0014
C:\Users\administrator\ObjectOperate\dataset_seq2fix\test\sean0032\objectd0018.png
test\sean0032\objectd0018
C:\Users\administrator\ObjectOperate\dataset_seq2fix\test\sean0041\objectd0025.png
test\sean0041\objectd0025
C:\Users\administrator\ObjectOperate\dataset_seq2fix\test\sean0045\objectd0028.png
test\sean0045\objectd0028
C:\Users\administrator\ObjectOperate\dataset_seq2fix\test\sean0053\objectd0025.png
test\sean0053\objectd0025
C:\Users\administrator\ObjectOperate\dataset_seq2fix\train\sean0000\objectd0000.png
train\sean0000\objectd0000
C:\Users\administ

In [26]:
img = PATH+"\\dataset_seq2fix\\test\\sean0032\\objectd0018_resize48.png"
image = Image.open(img)
img_array = np.asarray(image)
print(img_array)
img_array.flags.writeable = True
print(img_array.shape)
for i in range(img_array.shape[0]):
    for j in range(img_array.shape[1]):
        if img_array[i][j] != 0:
            img_array[i][j] += 400
print(img_array)
pil_img = Image.fromarray(img_array)
pil_img.save(PATH+"\\dataset_seq2fix\\test\\sean0032\\objectd0018_resize_fix48.png")

[[3300 3300 3299 ... 3261 3277 3277]
 [3284 3284 3294 ... 3283 3274 3274]
 [3284 3284 3294 ... 3283 3274 3274]
 ...
 [2938 2938 2939 ... 2940 2940 2940]
 [2938 2938 2939 ... 2940 2940 2940]
 [2923 2923 2922 ... 2938 2940 2940]]
(48, 48)
[[3700 3700 3699 ... 3661 3677 3677]
 [3684 3684 3694 ... 3683 3674 3674]
 [3684 3684 3694 ... 3683 3674 3674]
 ...
 [3338 3338 3339 ... 3340 3340 3340]
 [3338 3338 3339 ... 3340 3340 3340]
 [3323 3323 3322 ... 3338 3340 3340]]


In [ ]:
import torch
import torchvision
import torch.nn as nn
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt    #グラフ出力用module
from PIL import Image
from sklearn.model_selection import train_test_split
import glob
import os
import csv
import torchvision

img1 = PATH+"\\dataset_seq2fix\\train\\sean0011\\objectd0007_resize.png"
img2 = PATH+"\\dataset_seq2fix\\test\\sean0012\\objectd0008_resize.png"
lb1_dir = PATH+"\\dataset_seq2fix\\train\\sean0011\\down\\l"
lb2_dir = PATH+"\\dataset_seq2fix\\test\\sean0012\\down\\l"
evaltrain_seqs = []
evaltest_seqs = []
etr_labelfiles = glob.glob(lb1_dir+"\\*.csv")
ete_labelfiles = glob.glob(lb2_dir+"\\*.csv")
etelabel_seqs = []
etelabel_mseqs = []
for frame in range(len(etr_labelfiles)):
    with open(etr_labelfiles[frame]) as f:
        reader = csv.reader(f)
        num = 0
        for row in reader:
            if num == 0:
                elem = 1
                for p in row:
                    if (float(p) < -5000 or float(p) == 0):
                        invcnt += 1
                        etrlabel_seqs.append(float(0))
                        etrlabel_mseqs.append(float(0))
                    else:
                        etrlabel_seqs.append(float(p))
                        etrlabel_mseqs.append(float(1))
            num += 1
etrlabel_seqs = np.asarray(etrlabel_seqs)
etrlabel_mseqs = np.asarray(etrlabel_mseqs)
for frame in range(len(ete_labelfiles)):
    with open(ete_labelfiles[frame]) as f:
        reader = csv.reader(f)
        num = 0
        for row in reader:
            if num == 0:
                elem = 1
                for p in row:
                    if (float(p) < -5000 or float(p) == 0):
                        invcnt += 1
                        etelabel_seqs.append(float(0))
                        etelabel_mseqs.append(float(0))
                    else:
                        etelabel_seqs.append(float(p))
                        etelabel_mseqs.append(float(1))
            num += 1
etelabel_seqs = np.asarray(etelabel_seqs)
etelabel_mseqs = np.asarray(etelabel_mseqs)
image1 = Image.open(img1)
image2 = Image.open(img2)
img_array1 = np.asarray(image1)
img_array2 = np.asarray(image2)
img_etrlist = []
img_etelist = []
label_etrlist = []
label_etelist = []
lmask_etrlist = []
lmask_etelist = []
#img_list.append(img_array1)
img_etrlist.append(img_array1)
img_etelist.append(img_array2)
label_etrlist.append(etrlabel_seqs)
label_etelist.append(etelabel_seqs)
lmask_etrlist.append(etrlabel_mseqs)
lmask_etelist.append(etelabel_mseqs)
img_etrlistF = np.array(img_etrlist).astype('float32')/10000
img_etelistF = np.array(img_etelist).astype('float32')/10000
label_etrlistF = np.array(label_etrlist).astype('float32')/100
label_etelistF = np.array(label_etelist).astype('float32')/100
lmask_etrlistF = np.array(lmask_etrlist).astype('float32')
lmask_etelistF = np.array(lmask_etelist).astype('float32')
trans = torchvision.transforms.Compose(
    [torchvision.transforms.ToTensor()]#,torchvision.transforms.Normalize((0.5,0.5,0.5), (0.5,0.5,0.5))]
)
class Mydatasets(torch.utils.data.Dataset):
    def __init__(self, img, lb, lm transform = None):
        self.transform = transform
        #self.transform2 = torchvision.transforms.Compose([torchvision.transforms.ToTensor()])

        self.img = img
        self.lb = lb
        self.lm = lm
        self.datanum = img.shape[0]

    def __len__(self):
        return self.datanum

    def __getitem__(self, idx):
        #batch_set = []
        
        i_img = self.img[idx]
        i_lb = self.lb[idx]
        i_lm = self.lm[idx]
        
        o_img = np.array(i_img.astype(np.float32))
        o_lb = np.array(i_lb.astype(np.float32))
        o_lm = np.array(i_lm.astype(np.float32))
        
        if self.transform:
            o_img = self.transform(o_img)
            
        return o_img, o_lb, o_lm
etrset = Mydatasets(img = img_etrlistF, lb = label_etrlistF, lm = lmask_etrlistF, transform = trans)
eteset = Mydatasets(img = img_etelistF, lb = label_etelistF, lm = lmask_etelistF, transform = trans)
BATCH_SIZE = 1
etrlloader = torch.utils.data.DataLoader(etrset, batch_size = 1, shuffle = False, num_workers = 0)
etelloader = torch.utils.data.DataLoader(eteset, batch_size = 1, shuffle = False, num_workers = 0)
net.eval()
for (img, lb, lm) in etrloader:
    optimizer.zero_grad()
    img, lb, lm = img.to(device), lb.to(device), lm.to(device)
    out = net(img)
    loss = criterionM(out*100, lb*100, lm, lm)
    print(loss.item())
for (img, lb, lm) in eteloader:
    optimizer.zero_grad()
    img, lb, lm = img.to(device), lb.to(device), lm.to(device)
    out = net(img)
    loss = criterionM(out*100, lb*100, lm, lm)
    print(loss.item())