In [1]:
import torch
import torchvision
import torch.nn as nn
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt    #グラフ出力用module
from PIL import Image
from sklearn.model_selection import train_test_split
import glob
import os
import csv

In [8]:
a = torch.full((100, 5), fill_value = 4)
b = torch.empty(100, 5)
w = torch.Tensor(np.random.normal(size = (5, 5)))
for i in range(100):
    tmp = torch.full((1, 5), fill_value = i)
    b[i] = tmp
print("a: ", a)
print("b: ", b)
print("w: ", w)

a:  tensor([[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
      

In [11]:
at = torch.transpose(a)
c = torch.mul(a, w)
print(c)

TypeError: transpose() received an invalid combination of arguments - got (Tensor), but expected one of:
 * (Tensor input, name dim0, name dim1)
 * (Tensor input, int dim0, int dim1)


In [13]:
a = torch.randn([1, 2])
b = torch.randn([1, 2])
mse = nn.MSELoss()

result1 = mse(a, b)
result2 = torch.mean(torch.pow(torch.sub(a, b), 2))

print(a)
print(b)
print(result1.item())
print(result2.item())

tensor([[ 0.0456, -1.2158]])
tensor([[ 1.0365, -0.0524]])
1.167690396308899
1.167690396308899


In [27]:
a = torch.randn([5, 4])
b = torch.randn([5, 4])
mask = torch.tensor([[1.,0.,1.,1.],[1.,1.,1.,1.],[0.,0.,1.,1.],[1.,1.,1.,0.],[1.,1.,1.,1.]])
m_size = torch.tensor(mask.size()[1])
m_sum = torch.tensor(torch.sum(mask, 1))
print("m_size:",m_size)
print("m_sum:",m_sum)
rate = (m_size.item() / m_sum)
mse = nn.MSELoss()

masked_a = torch.mul(a, mask)
masked_b = torch.mul(b, mask)

result1 = mse(a, b)

#result2 = torch.mean(torch.pow(torch.sub(a, b), 2))
result2 = torch.sub(masked_a, masked_b)
print("sub2:",result2)
result2 = torch.pow(result2, 2)
print("pow2:",result2)
#result2 = torch.mean(result2)
#print("mean:",result2)
result2 = torch.sum(result2, 1)
print("sum2:",result2)
result2 = torch.mul(rate, result2)
print("gain2:",result2)
result2 = torch.mean(result2)
print("mean2:",result2)

result3 = torch.sub(a, b)
print("sub3:",result3)
result3 = torch.pow(result3, 2)
print("pow3:",result3)
#result2 = torch.mean(result2)
#print("mean:",result2)
result3 = torch.mean(result3, 1)
print("mean3:",result3)
result3 = torch.mean(result3)
print("mean3-2:",result3)

print("a:",a)
print("b:",b)
print("mask:",mask)
print("masked_a:",masked_a)
print("masked_b:",masked_b)

print("rate:",rate)
print("result1:",result1.item())
print("result2:",result2.item())

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """


m_size: tensor(4)
m_sum: tensor([3., 4., 2., 3., 4.])
sub2: tensor([[ 0.8265,  0.0000,  0.2559, -0.6920],
        [-1.8758, -0.6781,  0.6293,  0.4859],
        [ 0.0000, -0.0000, -2.1957,  0.1958],
        [ 0.5724,  2.8105,  1.0468,  0.0000],
        [ 1.1791, -0.4217, -0.4086,  0.1426]])
pow2: tensor([[0.6831, 0.0000, 0.0655, 0.4789],
        [3.5186, 0.4598, 0.3961, 0.2361],
        [0.0000, 0.0000, 4.8209, 0.0383],
        [0.3277, 7.8990, 1.0957, 0.0000],
        [1.3902, 0.1778, 0.1670, 0.0203]])
sum2: tensor([1.2274, 4.6107, 4.8592, 9.3224, 1.7553])
gain2: tensor([ 1.6366,  4.6107,  9.7185, 12.4299,  1.7553])
mean2: tensor(6.0302)
sub3: tensor([[ 0.8265,  0.7246,  0.2559, -0.6920],
        [-1.8758, -0.6781,  0.6293,  0.4859],
        [ 2.4452, -0.6773, -2.1957,  0.1958],
        [ 0.5724,  2.8105,  1.0468,  0.2383],
        [ 1.1791, -0.4217, -0.4086,  0.1426]])
pow3: tensor([[0.6831, 0.5250, 0.0655, 0.4789],
        [3.5186, 0.4598, 0.3961, 0.2361],
        [5.9792, 0.4587, 4.

In [31]:
c = torch.randn([1, 4])
d = torch.randn([5, 4])
bi = torch.tensor([1.,1.,1.,1.,1.])
print("c:",c)
print("d:",d)


result4 = torch.mul(c, d)
print(result4)
result4 = torch.sum(result4,1)
print(result4)
result4 = torch.add(result4, bi)
print(result4)                   

c: tensor([[-1.2316,  0.5826, -0.4310, -1.6540]])
d: tensor([[ 0.7979, -0.5406,  1.2781, -0.9086],
        [ 1.7596, -0.9857,  0.1605, -0.7632],
        [-0.5797, -0.1623, -0.1578, -2.0269],
        [ 0.0766,  1.0146,  0.4165, -0.1076],
        [-0.4543,  2.3152,  0.8006,  0.7786]])
tensor([[-0.9828, -0.3149, -0.5509,  1.5028],
        [-2.1672, -0.5743, -0.0692,  1.2623],
        [ 0.7140, -0.0945,  0.0680,  3.3524],
        [-0.0943,  0.5911, -0.1795,  0.1780],
        [ 0.5595,  1.3488, -0.3451, -1.2878]])
tensor([-0.3458, -1.5483,  4.0399,  0.4953,  0.2755])
tensor([ 0.6542, -0.5483,  5.0399,  1.4953,  1.2755])


In [32]:
e = torch.tensor([4.,4.,4.,4.])
f = torch.tensor([2.,1.,4.,0.5])

res5 = torch.div(e, f)
print(res5)

tensor([2., 4., 1., 8.])


In [41]:
from PIL import Image

image_size = 36

image = Image.open("C:\\Users\\arimoto\\ObjectOperate\\dataset\\sean0000\\objectd0000.png")
img_array = np.asarray(image)
image = image.resize((image_size, image_size))
img_array_resize = np.asarray(image)
print(img_array.shape)
print(img_array_resize.shape)
for i in range(img_array.shape[0]):
    print(img_array[i])
for i in range(img_array_resize.shape[0]):
    print(img_array_resize[i])

(97, 72)
(36, 36)
[3437 3435 3435 3435 3442 3442 3442 3442 3442 3442 3453 3453 3453 3451
 3451 3451 3442 3442 3442 3442 3442 3442 3434 3434 3434 3436 3436 3436
 3438 3438 3438 3437 3437 3437 3437 3437 3437 3432 3432 3432 3420 3420
 3420 3419 3419 3419 3429 3429 3429 3429 3429 3429 3433 3433 3433 3441
 3441 3441 3446 3446 3446 3438 3438 3438 3445 3445 3445 3446 3446 3446
 3449 3449]
[3437 3435 3435 3435 3442 3442 3442 3442 3442 3442 3453 3453 3453 3451
 3451 3451 3442 3442 3442 3442 3442 3442 3434 3434 3434 3436 3436 3436
 3438 3438 3438 3437 3437 3437 3437 3437 3437 3432 3432 3432 3420 3420
 3420 3419 3419 3419 3429 3429 3429 3429 3429 3429 3433 3433 3433 3441
 3441 3441 3446 3446 3446 3438 3438 3438 3445 3445 3445 3446 3446 3446
 3449 3449]
[3437 3435 3435 3435 3442 3442 3442 3442 3442 3442 3453 3453 3453 3451
 3451 3451 3442 3442 3442 3442 3442 3442 3434 3434 3434 3436 3436 3436
 3438 3438 3438 3437 3437 3437 3437 3437 3437 3432 3432 3432 3420 3420
 3420 3419 3419 3419 3429 3429 3429

 3347 3347]
[3360 3348 3348 3348 3335 3335 3335 3334 3334 3334 3320 3320 3320    0
    0    0 2975 2975 2975 2952 2952 2952 2942 2942 2942 2939 2939 2939
 2925 2925 2925 2920 2920 2920 2918 2918 2918 2922 2922 2922 2928 2928
 2928 2936 2936 2936 2934 2934 2934 2939 2939 2939 2951 2951 2951    0
    0    0    0    0    0    0    0    0 3331 3331 3331 3336 3336 3336
 3347 3347]
[3334 3322 3322 3322 3322 3322 3322 3315 3315 3315 3324 3324 3324    0
    0    0 2980 2980 2980 2949 2949 2949 2937 2937 2937 2929 2929 2929
 2926 2926 2926 2923 2923 2923 2923 2923 2923 2924 2924 2924 2930 2930
 2930 2933 2933 2933 2934 2934 2934 2939 2939 2939 2958 2958 2958 2994
 2994 2994    0    0    0    0    0    0 3308 3308 3308 3309 3309 3309
 3315 3315]
[3334 3322 3322 3322 3322 3322 3322 3315 3315 3315 3324 3324 3324    0
    0    0 2980 2980 2980 2949 2949 2949 2937 2937 2937 2929 2929 2929
 2926 2926 2926 2923 2923 2923 2923 2923 2923 2924 2924 2924 2930 2930
 2930 2933 2933 2933 2934 2934 2934 2939 

 3205 3205]
[3233 3235 3235 3235 3223 3223 3223 3215 3215 3215 3178 3178 3178 3106
 3106 3106 3026 3026 3026 2997 2997 2997 2978 2978 2978 2961 2961 2961
 2948 2948 2948 2950 2950 2950 2949 2949 2949 2948 2948 2948 2949 2949
 2949 2956 2956 2956 2965 2965 2965 2967 2967 2967 2978 2978 2978 2988
 2988 2988 3010 3010 3010    0    0    0    0    0    0 3209 3209 3209
 3205 3205]
[3233 3235 3235 3235 3223 3223 3223 3215 3215 3215 3178 3178 3178 3106
 3106 3106 3026 3026 3026 2997 2997 2997 2978 2978 2978 2961 2961 2961
 2948 2948 2948 2950 2950 2950 2949 2949 2949 2948 2948 2948 2949 2949
 2949 2956 2956 2956 2965 2965 2965 2967 2967 2967 2978 2978 2978 2988
 2988 2988 3010 3010 3010    0    0    0    0    0    0 3209 3209 3209
 3205 3205]
[3223 3220 3220 3220 3209 3209 3209 3208 3208 3208 3190 3190 3190    0
    0    0 3041 3041 3041 3010 3010 3010 2990 2990 2990 2971 2971 2971
 2952 2952 2952 2951 2951 2951 2949 2949 2949 2947 2947 2947 2948 2948
 2948 2958 2958 2958 2966 2966 2966 2974 

 3085 3085]
[3107 3117 3117 3117 3109 3109 3109 3097 3097 3097 3083 3083 3083 3073
 3073 3073 3057 3057 3057 3043 3043 3043 3031 3031 3031 3030 3030 3030
 3031 3031 3031 3025 3025 3025 3015 3015 3015 3008 3008 3008 3019 3019
 3019 3021 3021 3021 3002 3002 3002 2970 2970 2970 2957 2957 2957 2953
 2953 2953 2956 2956 2956 2955 2955 2955 2965 2965 2965 2981 2981 2981
    0    0]
[3107 3117 3117 3117 3109 3109 3109 3097 3097 3097 3083 3083 3083 3073
 3073 3073 3057 3057 3057 3043 3043 3043 3031 3031 3031 3030 3030 3030
 3031 3031 3031 3025 3025 3025 3015 3015 3015 3008 3008 3008 3019 3019
 3019 3021 3021 3021 3002 3002 3002 2970 2970 2970 2957 2957 2957 2953
 2953 2953 2956 2956 2956 2955 2955 2955 2965 2965 2965 2981 2981 2981
    0    0]
[3107 3117 3117 3117 3109 3109 3109 3097 3097 3097 3083 3083 3083 3073
 3073 3073 3057 3057 3057 3043 3043 3043 3031 3031 3031 3030 3030 3030
 3031 3031 3031 3025 3025 3025 3015 3015 3015 3008 3008 3008 3019 3019
 3019 3021 3021 3021 3002 3002 3002 2970 

 2943 2943]
[3020 3023 3023 3023 3010 3010 3010 3006 3006 3006 3003 3003 3003 3003
 3003 3003 3001 3001 3001 3002 3002 3002 3006 3006 3006 3008 3008 3008
 3009 3009 3009 3014 3014 3014 2996 2996 2996 2981 2981 2981 2979 2979
 2979 2966 2966 2966 2938 2938 2938 2918 2918 2918 2908 2908 2908 2909
 2909 2909 2909 2909 2909 2910 2910 2910 2909 2909 2909 2917 2917 2917
 2943 2943]
[3003 3009 3009 3009 2998 2998 2998 2996 2996 2996 2990 2990 2990 2994
 2994 2994 2992 2992 2992 2992 2992 2992 2994 2994 2994 2999 2999 2999
 3008 3008 3008 3010 3010 3010 3003 3003 3003 2991 2991 2991 2984 2984
 2984 2965 2965 2965 2938 2938 2938 2921 2921 2921 2911 2911 2911 2914
 2914 2914 2913 2913 2913 2915 2915 2915 2916 2916 2916 2922 2922 2922
 2949 2949]
[3003 3009 3009 3009 2998 2998 2998 2996 2996 2996 2990 2990 2990 2994
 2994 2994 2992 2992 2992 2992 2992 2992 2994 2994 2994 2999 2999 2999
 3008 3008 3008 3010 3010 3010 3003 3003 3003 2991 2991 2991 2984 2984
 2984 2965 2965 2965 2938 2938 2938 2921 

 2909 2909 2910 2910 2909 2917 2917 2943]
[3009 3009 2998 2996 2996 2990 2994 2994 2992 2992 2992 2994 2999 2999
 3008 3010 3010 3003 2991 2991 2984 2965 2965 2938 2921 2921 2911 2914
 2914 2913 2915 2915 2916 2922 2922 2949]


In [27]:
dim3 = torch.tensor([[[[0.5,0.5,1.,0.5],[2.,0.5,0.5,0.5]],[[1.1,-1.5,0.7,0.7],[0.7,0.7,0.7,0.2]]],
                     [[[0.5,0.5,0.5,0.5],[0.5,-0.6,0.5,0.7]],[[-0.4,0.7,0.7,0.7],[0.7,0.7,0.9,0.7]]]])
print("d3 size: ",dim3.size())

d3 size:  torch.Size([2, 2, 2, 4])


In [33]:
d3 = dim3.clone().detach()
print(d3)
print(d3.size())
print(d3.size()[0])
print("a: ",d3[:,0])
print("b: ",d3[:,1])
d3[:,0] = torch.sub(d3[:,0],0.5)
d3[:,1] = torch.sub(d3[:,1],0.7)
#for b in range(2):
#    print(b)
#    d3[:][0] = torch.sub(d3[:0], 0.5)
#    d3[:][1] = torch.sub(d3[:1::], 0.7)
print(d3)

tensor([[[[ 0.5000,  0.5000,  1.0000,  0.5000],
          [ 2.0000,  0.5000,  0.5000,  0.5000]],

         [[ 1.1000, -1.5000,  0.7000,  0.7000],
          [ 0.7000,  0.7000,  0.7000,  0.2000]]],


        [[[ 0.5000,  0.5000,  0.5000,  0.5000],
          [ 0.5000, -0.6000,  0.5000,  0.7000]],

         [[-0.4000,  0.7000,  0.7000,  0.7000],
          [ 0.7000,  0.7000,  0.9000,  0.7000]]]])
torch.Size([2, 2, 2, 4])
2
a:  tensor([[[ 0.5000,  0.5000,  1.0000,  0.5000],
         [ 2.0000,  0.5000,  0.5000,  0.5000]],

        [[ 0.5000,  0.5000,  0.5000,  0.5000],
         [ 0.5000, -0.6000,  0.5000,  0.7000]]])
b:  tensor([[[ 1.1000, -1.5000,  0.7000,  0.7000],
         [ 0.7000,  0.7000,  0.7000,  0.2000]],

        [[-0.4000,  0.7000,  0.7000,  0.7000],
         [ 0.7000,  0.7000,  0.9000,  0.7000]]])
tensor([[[[ 0.0000,  0.0000,  0.5000,  0.0000],
          [ 1.5000,  0.0000,  0.0000,  0.0000]],

         [[ 0.4000, -2.2000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000, -0

In [25]:
0 ** 0

1

In [41]:
a = torch.tensor([False,True,True]).float()
print(a)

tensor([0., 1., 1.])


In [35]:
0. and 1

0.0

In [36]:
0.0 or 1.0

1.0

In [37]:
int(False)

0

In [38]:
float(False)

0.0

In [39]:
float(True)

1.0

In [7]:
a = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[12,13,14],[15,16,17]])
b = torch.tensor([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
print(a.shape)
print(b.shape)
print(a)
print(b)
print(a[:,0])
print(b[:,0])

torch.Size([6, 3])
torch.Size([6, 2])
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [12, 13, 14],
        [15, 16, 17]])
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]])
tensor([ 1,  4,  7, 10, 12, 15])
tensor([ 1,  3,  5,  7,  9, 11])


In [6]:
a = torch.tensor([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18]])
print(torch.cat((a[:,0:2],a[:,4:6]),1))
print(a[:,3:6])

tensor([[ 1,  2,  5,  6],
        [ 7,  8, 11, 12],
        [13, 14, 17, 18]])
tensor([[ 4,  5,  6],
        [10, 11, 12],
        [16, 17, 18]])


In [7]:
a = torch.tensor()

TypeError: tensor() missing 1 required positional arguments: "data"